import { Product } from './types';

export const productsData: Product[] = [
  {
    id: '1',
    nameKg: 'Колго жасалган Салттуу Курут',
    nameRu: 'Курут Классический (королевский)',
    descriptionKg: 'Байыркы кочмөндөрдүн ыкмасы менен Кара-Сууда даярдалган кургатылган накта курут. Туздуу, катуу жана өтө пайдалуу улуттук азык.',
    descriptionRu: 'Натуральный сушеный курут из Кара-Суу, умеренно соленый, плотный, приготовленный вручную на 100% из цельного молока.',
    price: 450,
    wholesalePrice: 380,
    minWholesaleQty: 10,
    volumeKg: '1 кг',
    volumeRu: '1 кг',
    category: 'dried',
    isWholesaleAvailable: true,
    image: '/src/assets/images/kyrgyz_dairy_products_1781253983506.jpg', // Our generated masterpiece!
    rating: 5.0,
    availability: 'in_stock',
  },
  {
    id: '2',
    nameKg: 'Сүттүү Шербет (Сергитүүчү суусундук)',
    nameRu: 'Молочный Шербет (Ферментированный drink)',
    descriptionKg: 'Жайлоонун таза чөптөрү жана табигый ачытылган сүттөн даярдалган улуттук муздак суусундук. Организмди сергитет.',
    descriptionRu: 'Традиционный прохладительный кисломолочный напиток с добавлением целебных горных трав Кара-Суу. Отлично утоляет жажду.',
    price: 90,
    wholesalePrice: 75,
    minWholesaleQty: 30,
    volumeKg: '1 литр',
    volumeRu: '1 литр',
    category: 'fresh',
    isWholesaleAvailable: true,
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=600&q=80', // Beautiful jug image (dairy/milk/sherbet feel)
    rating: 4.8,
    availability: 'in_stock',
  },
  {
    id: '3',
    nameKg: 'Ала-Тоо Сар Майы (Эритилген)',
    nameRu: 'Табигый Сары Май (Топленое масло)',
    descriptionKg: 'Күн тийген Ош жайлоолорунун накта каймагынан эритилип алынган, өзгөчө жагымдуу даамы бар алтын түстүү сары май.',
    descriptionRu: 'Золотистое топленое сливочное масло, приготовленное по старинному рецепту из чистейших коровьих сливок высокогорной выработки.',
    price: 850,
    wholesalePrice: 750,
    minWholesaleQty: 5,
    volumeKg: '1 кг',
    volumeRu: '1 кг',
    category: 'butter',
    isWholesaleAvailable: true,
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80', // Golden dairy / yellow fat
    rating: 4.9,
    availability: 'in_stock',
  },
  {
    id: '4',
    nameKg: 'Тоолук Коюу Айран (Уютку кошулган)',
    nameRu: 'Айран Домашний Кара-Суу',
    descriptionKg: 'Сапаттуу жана таза сүттөн атайын тоолук сыр менен ачытылып жасалган абдан коюу жана даамдуу айран. Сиңимдүү.',
    descriptionRu: 'Густой классический айран высокой жирности, заквашенный на традиционной живой культуре. Полезен для ЖКТ.',
    price: 70,
    wholesalePrice: 55,
    minWholesaleQty: 15,
    volumeKg: '1 кг (банка)',
    volumeRu: '1 кг (банка)',
    category: 'fresh',
    isWholesaleAvailable: true,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80', // Glass jar of dairy desert / yogurt
    rating: 4.7,
    availability: 'in_stock',
  },
  {
    id: '5',
    nameKg: 'Накта Тоолук Каймак',
    nameRu: 'Каймак Густой (Сливки домашние)',
    descriptionKg: 'Кара-Суу районунун дыйкандарынан эртең менен жаңы саалып келинген сүттү тартып даярдалган, коюу жана ооздо эриген каймак.',
    descriptionRu: 'Свежайшие густые деревенские сливки, взбитые по классической технологии. Имеют сладковатый нежный сливочный вкус.',
    price: 320,
    wholesalePrice: 270,
    minWholesaleQty: 10,
    volumeKg: '400 грамм',
    volumeRu: '400 грамм',
    category: 'butter',
    isWholesaleAvailable: true,
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=600&q=80', // White cream in a bowl / sandwich cream
    rating: 4.9,
    availability: 'limited',
  },
  {
    id: '6',
    nameKg: 'Ышталып Даярдалган Өзгөчө Курут',
    nameRu: 'Курут Копченый (Ароматный)',
    descriptionKg: 'Экологиялык таза алма жана өрүк жыгачтарынын түтүнүндө атайын усул менен ышталып даярдалган эң даамдуу куймактуу курут.',
    descriptionRu: 'Пряный курут премиум качества, подкопченный на натуральных опилках плодовых деревьев. Хрустящий вкус с дымком.',
    price: 280,
    wholesalePrice: 240,
    minWholesaleQty: 10,
    volumeKg: '500 грамм',
    volumeRu: '500 грамм',
    category: 'dried',
    isWholesaleAvailable: true,
    image: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=600&q=80', // Smoked cheese spheres or balls
    rating: 4.8,
    availability: 'in_stock',
  },
  {
    id: '7',
    nameKg: 'Жайлоо Сузмөсү',
    nameRu: 'Сузьма Домашняя (Творожная масса)',
    descriptionKg: 'Сүттүн сары суусун сүзүп даярдалган, витамин жана минералдарга бай, коюу улуттук сүзмө. Көк кошуп жегенге пайдалуу.',
    descriptionRu: 'Густая процеженная кисломолочная масса (сузьма), чистый белок. Идеальна для приготовления соусов или употребления со специями.',
    price: 220,
    wholesalePrice: 180,
    minWholesaleQty: 10,
    volumeKg: '1 кг',
    volumeRu: '1 кг',
    category: 'fresh',
    isWholesaleAvailable: true,
    image: 'https://images.unsplash.com/photo-1571244856341-4f3dd95db36e?auto=format&fit=crop&w=600&q=80', // Curded white food
    rating: 4.6,
    availability: 'in_stock',
  },
  {
    id: '8',
    nameKg: 'Бийик Тоо Шыпаалуу Кымызы',
    nameRu: 'Кымыз Настоящий (Кобылье молоко)',
    descriptionKg: 'Ала-Тоонун улуу бийиктиктеринде багылган бээлердин таза кымызы. Ден соолукка, өпкөгө өтө сонун шыпаасы бар.',
    descriptionRu: 'Оригинальный ферментированный кобылий напиток (кумыс) весенней закваски. Известен своими лечебными свойствами.',
    price: 180,
    wholesalePrice: 150,
    minWholesaleQty: 15,
    volumeKg: '1.5 литра',
    volumeRu: '1.5 литра',
    category: 'fresh',
    isWholesaleAvailable: true,
    image: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&w=600&q=80', // Liquid pour / natural drinks
    rating: 5.0,
    availability: 'limited',
  }
];
